on:
  push:
    branches:
      - main

jobs:
  deploy_to_cloud_functions:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: 'Deploy the functions using gcloud CLI'
        run: 'gcloud functions deploy auctions_scrapping --gen2 --region=us-east1 --runtime=nodejs18 --source=. --entry-point=initScrapping --trigger-http'
